### ISSUE TITLE
[Epic] Revamp specator mode

### ISSUE THREAD

**Issue by HexaField** [ir-engine/etherealengine-archive#10031]
Tech Debt
- [x] #10053

Feature
- [ ] Redesign user story for spectator mode
- [ ] Reimplement spectator system
- [ ] QA
- [ ] QA spectate invites
