### ISSUE TITLE
[Epic] Load GLTF straight into the ECS

### ISSUE THREAD

**Issue by HexaField** [ir-engine/etherealengine-archive#10049]
- [x] #10050
- [ ] Scene state snapshots store GLTF documents instead of entity json
- [ ] Reimplement editor control functions with gltf-transform
- [ ] GLTF loader should create entity hierarchy instead of us parsing the threejs object hierarchy
- [ ] GLTF based SceneLoadingSystem to deserialize changes straight into the ECS
- [ ] Scene JSON format becomes deprecated/redundant
