### ISSUE TITLE
[Epic] Rework assets & static resources

### ISSUE THREAD

**Issue by HexaField** [ir-engine/etherealengine-archive#10086]
- [ ] Introduce assets table as a replacement for scene service
- [ ] https://github.com/EtherealEngine/etherealengine/issues/9903
- [ ] Rework `resources.json` to be a partial, and only have deployment-independent info (hash, tags), and include asset entries
- [ ] Ensure file browser API is always used for CMS instead of static resources
- [ ] Move thumbnails field to asset table
- [ ] Asset table populated and updated for all GLTFs
