### ISSUE TITLE
[EPIC]: Asset Pipeline Optimizations

### ISSUE THREAD

**Issue by HexaField** [ir-engine/etherealengine-archive#6312]
- [ ] https://github.com/XRFoundation/XREngine/issues/4512
- [x] https://github.com/XRFoundation/XREngine/issues/5373
- [x] https://github.com/XRFoundation/XREngine/issues/5518
- [ ] https://github.com/XRFoundation/XREngine/issues/5491
- [x] https://github.com/XRFoundation/XREngine/issues/5383
- [ ] https://github.com/XRFoundation/XREngine/issues/5448
- [ ] https://github.com/XRFoundation/XREngine/issues/5509
- [x] https://github.com/XRFoundation/XREngine/issues/5835
