### ISSUE TITLE
[Epic] Project Versioning

### ISSUE THREAD

**Issue by HexaField** [ir-engine/etherealengine-archive#9749]
- [x] Add script to install projects from manifest
  - [x] Checks out to specific branch
  - [x] npm run install-manifest -- --manifestURL="https://raw.githubusercontent.com/EtherealEngine/project-manifest/main/manifest.json" --branch="dev"
- [x] Add git checkout dev script
- [x] Default all scripts to main branch
- [x] Add main & dev branches for every project
- [x] Default all projects to dev branch
- [x] Lock down perms on all projects
- [x] Disable projects that having incorrect engine version number
- [ ] Rename `etherealEngine` property in project package.json to `engineVersion`
- [ ] Add CLI & GHA scripts to help automate updates & releases
  - [ ] Change updating dev version to after the release is made
  - [ ] Auto-merge engine release update PR
  - [ ] Upon tag being created in etherealengine repo, run workflow in all projects
    - [ ] Launch project update workflow for release event for engine https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release 
  - [ ] Add a PR with the changes to the version number
- [ ] How can we automatically create main & dev branches for every project?
  - [x] npm run create-project – –name=”ee-new-project”
  - [ ] Can we automate branch protection?
- [ ] Add CI/CD for all projects, and include all open source projects in engine CI/CD with branch name matching
  - [ ] Once engine PR is closed or merged, close or merge all related PRs
- [ ] Test tag flow & create tag releases
- [ ] Force projects to have org namespace in project name (yet still allow esm imports…)
  - [ ] Symlinking with org namespaces seems to work
  - [ ] We need to change the folder structure to be /packages/projects/projects/<@namespace>/<project-name>
