### ISSUE TITLE
[Epic] Transform Gizmo

### ISSUE THREAD

**Issue by HexaField** [ir-engine/etherealengine-archive#9784]
- [x] https://github.com/EtherealEngine/etherealengine/issues/9776
- [ ] https://github.com/EtherealEngine/etherealengine/issues/9782
- [x] https://github.com/EtherealEngine/etherealengine/issues/9783
- [x] https://github.com/EtherealEngine/etherealengine/issues/9775
- [ ] Stabilize and write tests
